name: Markdown Lint

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"
      - ".markdownlint.yml"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"
      - ".markdownlint.yml"

permissions:
  contents: read

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: ".markdownlint.yml"
          globs: |
            **/*.md
            !**/.terraform/**
